/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package modelisation.billetterie;

import javax.swing.UIManager;

import com.formdev.flatlaf.intellijthemes.FlatVuesionIJTheme;
import javax.swing.UnsupportedLookAndFeelException;





/**
 *
 * @author Vanessa Kenniche & Thomas Fernandes
 */
public class Accueil extends javax.swing.JFrame {

    /**
     * Creates new form Accueil
     */
    public Accueil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1Nouveau = new javax.swing.JButton();
        jButton2Existant = new javax.swing.JButton();
        jButton3Visualisation = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Billetterie");

        jButton1Nouveau.setText("Nouveau client");
        jButton1Nouveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1NouveauActionPerformed(evt);
            }
        });

        jButton2Existant.setText("Client existant");
        jButton2Existant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ExistantActionPerformed(evt);
            }
        });

        jButton3Visualisation.setText("Gestionnaire des clients");
        jButton3Visualisation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3VisualisationActionPerformed(evt);
            }
        });

        jButton1.setText("Quitter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3Visualisation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1Nouveau, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2Existant, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addComponent(jButton1Nouveau)
                .addGap(18, 18, 18)
                .addComponent(jButton2Existant)
                .addGap(18, 18, 18)
                .addComponent(jButton3Visualisation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Bouton de redirection vers la billeterie
    private void jButton1NouveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1NouveauActionPerformed
        Billetterie b = new Billetterie();
        b.show();
        dispose();
    }//GEN-LAST:event_jButton1NouveauActionPerformed

    //Bouton de redirection vers l'interface client
    private void jButton2ExistantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ExistantActionPerformed
         InterfaceClient ic = new InterfaceClient();
         ic.show();
         dispose();
    }//GEN-LAST:event_jButton2ExistantActionPerformed

    //Bouton de redirection vers la visualisation des clients
    private void jButton3VisualisationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3VisualisationActionPerformed
        VisualisationClients vc = new VisualisationClients();
         vc.show();
         dispose();
    }//GEN-LAST:event_jButton3VisualisationActionPerformed

    //Bouton pour fermer le formulaire et quitter l'application
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new FlatVuesionIJTheme());
        } catch (UnsupportedLookAndFeelException e){
            e.printStackTrace();
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Accueil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton1Nouveau;
    private javax.swing.JButton jButton2Existant;
    private javax.swing.JButton jButton3Visualisation;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
