/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package modelisation.billetterie;

import com.formdev.flatlaf.FlatDarkLaf;
import java.text.DecimalFormat;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Vanessa Kenniche & Thomas Fernandes
 */
public class NouveauBillet extends javax.swing.JFrame {

    /**
     * Creates new form NouveauBillet
     */
    
    public NouveauBillet() {
        initComponents();
        reducFid = 0;
        setReducFidelite();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldPrenom        = new javax.swing.JTextField();
        jTextFieldReduction     = new javax.swing.JTextField();
        jTextFieldReducFidelite = new javax.swing.JTextField();
        jTextFieldPrixFinal     = new javax.swing.JTextField();
        jButtonConfirmer = new javax.swing.JButton();
        jButton1         = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jCheckBoxFid = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Acheter un nouveau billet pour ");

        jTextFieldPrenom.setEditable(false);
        jTextFieldPrenom.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextFieldPrenom.setBorder(null);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "T1 : 50e 20 attractions", "T2 : 70e 45 attractions", "T3 : 85e Attractions illimitees" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButtonConfirmer.setText("Confirmer");
        jButtonConfirmer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmerActionPerformed(evt);
            }
        });

        jLabel2.setText("Réduction Catégorie");

        jTextFieldReduction.setEditable(false);
        jTextFieldReduction.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton1.setText("Annuler");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Réduction Fidélité");

        jTextFieldReducFidelite.setEditable(false);
        jTextFieldReducFidelite.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jCheckBoxFid.setText("Utilisation points de fidelité");
        jCheckBoxFid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxFidActionPerformed(evt);
            }
        });

        jLabel4.setText("Prix Final");

        jTextFieldPrixFinal.setEditable(false);
        jTextFieldPrixFinal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(24, 24, 24))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButtonConfirmer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextFieldPrixFinal, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                        .addComponent(jTextFieldReducFidelite, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                        .addComponent(jTextFieldReduction))
                                    .addGap(49, 49, 49)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jCheckBoxFid)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldReduction, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldReducFidelite, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jCheckBoxFid))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPrixFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConfirmer)
                    .addComponent(jButton1))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private double reducFid;
    private String ligne = "";
    Calcul cal = new Calcul();
    Client client = cal.clientvide;
    
    //Affiche le prénom du client et la réduction dispo liée à sa catégorie
    public void setClient(Client c){
        client = c;
        Calcul cal = new Calcul(Integer.valueOf(c.getNaiAnnee()), "");
        jTextFieldPrenom.setText(c.getPrenom());
        jTextFieldReduction.setText(cal.getReduc());
    }
    
    //Calcul de la valeur de la reduction de fidélité, nb_points/66 = réduction en euros
    //Utilisation de DecimalFormat pour limiter le nombre de chiffres après la virgule
    public void setReducFidelite(){
        WriterReader WR = new WriterReader();
        WR.ScannerGeneral(client);
        ligne = WR.getLigneOut();
        String[] ps = ligne.split(",");
        String billet = (String) jComboBox1.getSelectedItem();
        
        double reducFidelite = (Double.valueOf(ps[11]) / 66);
        DecimalFormat df = new DecimalFormat("####0.00");
        jTextFieldReducFidelite.setText(String.valueOf(df.format(reducFidelite)) + "€");
        this.reducFid =  reducFidelite;
    }
    
    //Méthode de calcul du prix du billet compte tenu des réductions et des
    //points de fidelité ou non
    public void prixFinal(){
        double prix      = 0;
        double reduction = 0;
        double prixFinal = 0;
        String[] ps = ligne.split(",");
        String billet = (String) jComboBox1.getSelectedItem();
        Calcul cal = new Calcul(Integer.valueOf(ps[5]), billet);
        prix = cal.getPrix();
        reduction = cal.reduc();
        
        if (jCheckBoxFid.isSelected())
            prixFinal = (prix - prix * reduction) - reducFid;
        else
            prixFinal = (prix - prix * reduction);
        
        DecimalFormat df = new DecimalFormat("####0.00");
        jTextFieldPrixFinal.setText(df.format(prixFinal));
    }
    
    //Modifie le dernier billet acheté par le client et son nombre de points
    //restant dans le CSV
    private void jButtonConfirmerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmerActionPerformed
        WriterReader WR = new WriterReader();
        WR.ScannerGeneral(client);
        ligne = WR.getLigneOut();
        String[] ps   = ligne.split(",");
        String billet = (String) jComboBox1.getSelectedItem();
        
        //Calcul du nouveau nombre de points de fidélité
        int anneeCalcul = Integer.valueOf(ps[5]); 
        Calcul cal      = new Calcul(anneeCalcul, billet);
        String fidelite = cal.getStringFidelite();
        
        //Si le client n'utilise pas ses points de fidelité, il récupère ceux qu'il avait en plus des nouveaux
        int fideliteInt = 0;
        if (jCheckBoxFid.isSelected())
            fideliteInt = Integer.valueOf(fidelite);
        else
            fideliteInt = Integer.valueOf(ps[11]) + Integer.valueOf(fidelite);
        
        String fide  = Integer.toString(fideliteInt);
        String ready = String.format(ps[0]+","+ps[1]+","+ps[2]+","+ps[3]+","+ps[4]+","+ps[5]+","+ps[6]+","+ps[7]+","+ps[8]+","+billet+","+ps[10]+","+fide);
        
        EditDelete ED = new EditDelete();
        ED.setNewClient(ready);
        ED.Delete(client);
        dispose();
    }//GEN-LAST:event_jButtonConfirmerActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    //Bouton de fermeture de la fenêtre
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    //Si l'item sélectionné change, le montant du prix final change aussi
    //Nouvel appel de la méthode prix final
    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        prixFinal();
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    //Le prix final change si le client veut utiliser ses points ou non
    private void jCheckBoxFidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxFidActionPerformed
        prixFinal();
    }//GEN-LAST:event_jCheckBoxFidActionPerformed

    //Si le premier appel de prix final était effectué dans le constructeur,
    //le prix final serait de 0, tant que le client n'aurait pas effectué 
    //l'un des Event Java Swing ci-dessus, on fait donc appel à la méthode prixFinal()
    //à l'ouverture de la fenêtre
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        prixFinal();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new FlatDarkLaf());
        } catch (UnsupportedLookAndFeelException e){
            e.printStackTrace();
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NouveauBillet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonConfirmer;
    private javax.swing.JCheckBox jCheckBoxFid;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextFieldPrenom;
    private javax.swing.JTextField jTextFieldPrixFinal;
    private javax.swing.JTextField jTextFieldReducFidelite;
    private javax.swing.JTextField jTextFieldReduction;
    // End of variables declaration//GEN-END:variables
}
